# Generated by Django 6.0.4 on 2026-05-02 05:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='drama',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('original_title', models.CharField(max_length=512)),
                ('description', models.CharField(max_length=1024)),
                ('last_watched_ep', models.IntegerField()),
                ('last_released_ep', models.IntegerField()),
                ('total_ep', models.IntegerField()),
                ('watch_status', models.CharField(max_length=32)),
                ('last_watched_ep_info', models.CharField(max_length=1024)),
                ('next_ep_release_date', models.DateField()),
                ('thumbnail_img', models.URLField()),
                ('notes', models.CharField(max_length=4096)),
            ],
        ),
    ]
