# Generated by Django 6.0.4 on 2026-05-03 04:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='description',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='last_released_ep',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='last_watched_ep',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='last_watched_ep_info',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='next_ep_release_date',
        ),
        migrations.RemoveField(
            model_name='drama',
            name='watch_status',
        ),
        migrations.CreateModel(
            name='watching_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watched_ep', models.IntegerField()),
                ('last_released_ep', models.IntegerField()),
                ('watch_status', models.CharField(max_length=32)),
                ('last_watched_ep_info', models.CharField(max_length=1024)),
                ('next_ep_release_date', models.DateField()),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='holics.drama')),
            ],
        ),
    ]
