# Generated by Django 6.0.4 on 2026-05-03 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0002_remove_drama_description_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watching_status',
            old_name='title',
            new_name='drama',
        ),
    ]
