# Generated by Django 6.0.4 on 2026-05-03 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0003_rename_title_watching_status_drama'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watching_status',
            name='drama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchstat', to='holics.drama'),
        ),
    ]
