# Generated by Django 6.0.4 on 2026-05-03 08:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0004_alter_watching_status_drama'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drama',
            name='notes',
        ),
        migrations.CreateModel(
            name='user_watching_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watched_ep', models.IntegerField()),
                ('last_released_ep', models.IntegerField()),
                ('watch_status', models.CharField(max_length=32)),
                ('last_watched_ep_info', models.CharField(max_length=1024)),
                ('next_ep_release_date', models.DateField()),
                ('notes', models.CharField(max_length=4096)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchstat', to='holics.drama')),
            ],
        ),
        migrations.DeleteModel(
            name='watching_status',
        ),
    ]
