# Generated by Django 6.0.4 on 2026-05-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0005_remove_drama_notes_user_watching_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_watching_status',
            name='watch_status',
        ),
        migrations.AlterField(
            model_name='user_watching_status',
            name='next_ep_release_date',
            field=models.DateField(null=True),
        ),
    ]
