# Generated by Django 6.0.4 on 2026-05-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0006_remove_user_watching_status_watch_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_watching_status',
            name='watch_status',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='user_watching_status',
            name='last_released_ep',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='user_watching_status',
            name='last_watched_ep_info',
            field=models.CharField(max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user_watching_status',
            name='notes',
            field=models.CharField(max_length=4096, null=True),
        ),
    ]
