# Generated by Django 6.0.4 on 2026-05-03 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0007_user_watching_status_watch_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_watching_status',
            name='last_released_ep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_watching_status',
            name='last_watched_ep_info',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AlterField(
            model_name='user_watching_status',
            name='next_ep_release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_watching_status',
            name='notes',
            field=models.CharField(blank=True, max_length=4096, null=True),
        ),
        migrations.AlterField(
            model_name='user_watching_status',
            name='watch_status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
