# Generated by Django 6.0.4 on 2026-05-05 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0008_alter_user_watching_status_last_released_ep_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='thumbnail_img',
            field=models.URLField(null=True),
        ),
    ]
