# Generated by Django 6.0.4 on 2026-05-14 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0009_alter_drama_thumbnail_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='animes',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('original_title', models.CharField(max_length=512)),
                ('total_ep', models.IntegerField()),
                ('thumbnail_img', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_drama_watching_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watched_ep', models.IntegerField()),
                ('last_released_ep', models.IntegerField(blank=True, null=True)),
                ('watch_status', models.CharField(blank=True, max_length=32, null=True)),
                ('last_watched_ep_info', models.CharField(blank=True, max_length=1024, null=True)),
                ('next_ep_release_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=4096, null=True)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchstat', to='holics.animes')),
            ],
        ),
        migrations.DeleteModel(
            name='user_watching_status',
        ),
    ]
