# Generated by Django 6.0.4 on 2026-05-14 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0010_animes_user_drama_watching_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_drama_watching_status',
            name='drama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchstat', to='holics.drama'),
        ),
        migrations.CreateModel(
            name='user_anime_watching_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_watched_ep', models.IntegerField()),
                ('last_released_ep', models.IntegerField(blank=True, null=True)),
                ('watch_status', models.CharField(blank=True, max_length=32, null=True)),
                ('last_watched_ep_info', models.CharField(blank=True, max_length=1024, null=True)),
                ('next_ep_release_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=4096, null=True)),
                ('drama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchstat', to='holics.animes')),
            ],
        ),
    ]
