# Generated by Django 6.0.4 on 2026-05-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0011_alter_user_drama_watching_status_drama_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_anime_watching_status',
            old_name='drama',
            new_name='anime',
        ),
        migrations.AddField(
            model_name='animes',
            name='status',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
