# Generated by Django 6.0.4 on 2026-05-15 11:38

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0012_rename_drama_user_anime_watching_status_anime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='dramas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('original_title', models.CharField(blank=True, max_length=512, null=True)),
                ('total_ep', models.IntegerField(blank=True, null=True)),
                ('thumbnail_img', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='mangas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('original_title', models.CharField(blank=True, max_length=512, null=True)),
                ('total_ep', models.IntegerField(blank=True, null=True)),
                ('thumbnail_img', models.URLField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_anime_watching_status',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user_drama_watching_status',
            name='season',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animes',
            name='original_title',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='animes',
            name='thumbnail_img',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='animes',
            name='total_ep',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user_anime_watching_status',
            name='anime',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ani_watchstat', to='holics.animes'),
        ),
        migrations.AlterField(
            model_name='user_drama_watching_status',
            name='drama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drama_watchstat', to='holics.dramas'),
        ),
        migrations.CreateModel(
            name='user_manga_watching_status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season', models.IntegerField(blank=True, null=True)),
                ('last_watched_ep', models.IntegerField()),
                ('last_released_ep', models.IntegerField(blank=True, null=True)),
                ('watch_status', models.CharField(blank=True, max_length=32, null=True)),
                ('last_watched_ep_info', models.CharField(blank=True, max_length=1024, null=True)),
                ('next_ep_release_date', models.DateField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=4096, null=True)),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ani_watchstat', to='holics.mangas')),
            ],
        ),
        migrations.DeleteModel(
            name='drama',
        ),
    ]
