# Generated by Django 6.0.4 on 2026-05-15 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0013_dramas_mangas_user_anime_watching_status_season_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_manga_watching_status',
            name='manga',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manga_watchstat', to='holics.mangas'),
        ),
    ]
