# Generated by Django 6.0.4 on 2026-05-23 01:45

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0014_alter_user_manga_watching_status_manga'),
    ]

    operations = [
        migrations.CreateModel(
            name='movies',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=512)),
                ('original_title', models.CharField(blank=True, max_length=512, null=True)),
                ('thumbnail_img', models.URLField(null=True)),
                ('release_date', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_movie_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_status', models.CharField(blank=True, max_length=32, null=True)),
                ('notes', models.CharField(blank=True, max_length=4096, null=True)),
                ('like', models.BooleanField(default=False)),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_notes', to='holics.dramas')),
            ],
        ),
    ]
