# Generated by Django 6.0.4 on 2026-05-24 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0015_movies_user_movie_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='dramas',
            name='max_season',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
