# Generated by Django 6.0.4 on 2026-05-26 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0016_dramas_max_season'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_anime_watching_status',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_drama_watching_status',
            name='like',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user_manga_watching_status',
            name='like',
            field=models.BooleanField(default=False),
        ),
    ]
