# Generated by Django 6.0.4 on 2026-05-26 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('holics', '0017_user_anime_watching_status_like_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_movie_data',
            name='movies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_notes', to='holics.movies'),
        ),
    ]
